// Generated by gencpp from file ssddetect/BoundingBoxes.msg
// DO NOT EDIT!


#ifndef SSDDETECT_MESSAGE_BOUNDINGBOXES_H
#define SSDDETECT_MESSAGE_BOUNDINGBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ssddetect/BoundingBox.h>

namespace ssddetect
{
template <class ContainerAllocator>
struct BoundingBoxes_
{
  typedef BoundingBoxes_<ContainerAllocator> Type;

  BoundingBoxes_()
    : header()
    , boundingBoxes()  {
    }
  BoundingBoxes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boundingBoxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ssddetect::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ssddetect::BoundingBox_<ContainerAllocator> >::other >  _boundingBoxes_type;
  _boundingBoxes_type boundingBoxes;




  typedef boost::shared_ptr< ::ssddetect::BoundingBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ssddetect::BoundingBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBoxes_

typedef ::ssddetect::BoundingBoxes_<std::allocator<void> > BoundingBoxes;

typedef boost::shared_ptr< ::ssddetect::BoundingBoxes > BoundingBoxesPtr;
typedef boost::shared_ptr< ::ssddetect::BoundingBoxes const> BoundingBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ssddetect::BoundingBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ssddetect::BoundingBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ssddetect

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ssddetect': ['/media/ziwei/Harddisk02/HanBin/TOOL/workspace_C++/Detect/src/SSDdetect/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ssddetect::BoundingBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ssddetect::BoundingBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ssddetect::BoundingBoxes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b3add6f6b751ce1e4ba418832812a17";
  }

  static const char* value(const ::ssddetect::BoundingBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b3add6f6b751ce1ULL;
  static const uint64_t static_value2 = 0xe4ba418832812a17ULL;
};

template<class ContainerAllocator>
struct DataType< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ssddetect/BoundingBoxes";
  }

  static const char* value(const ::ssddetect::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
BoundingBox[] boundingBoxes\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ssddetect/BoundingBox\n\
string Class\n\
float64 probability\n\
int64 xmin\n\
int64 ymin\n\
int64 width\n\
int64 height\n\
\n\
";
  }

  static const char* value(const ::ssddetect::BoundingBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boundingBoxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ssddetect::BoundingBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ssddetect::BoundingBoxes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boundingBoxes[]" << std::endl;
    for (size_t i = 0; i < v.boundingBoxes.size(); ++i)
    {
      s << indent << "  boundingBoxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ssddetect::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.boundingBoxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSDDETECT_MESSAGE_BOUNDINGBOXES_H
