yolo_model:
  config_file:
    name: gaussian_person_face.cfg
  graph_file:
    name: gaussian_person_face_graph
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - face

