yolo_model:

  config_file:
    name: tiny-yolo-voc.cfg
  graph_file:
    name: tiny-yolo-voc_graph
  threshold:
    value: 0.3
  detection_classes:
    names:
      - aeroplane
      - bicycle
      - bird
      - boat
      - bottle
      - bus
      - car
      - cat
      - chair
      - cow
      - dining table
      - dog
      - horse
      - motorbike
      - person
      - potted plant
      - sheep
      - sofa
      - train
      - tv monitor
